apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-webclient-rs
  labels:
    app: redis-webclient
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-webclient
  template:
    metadata:
      name: redis-webclient
      labels:
        app: redis-webclient
    spec:
      containers:
      - name: redis-webclient
      image: piotrbrodzinski/webclient:0.0.1
      ports:
        - containerPort: 80
          name: redis-webclient-container-port
      envFrom:
         - configMapRef:
             name: redis-webclient-config 